name: "Push Simple App to Win Server"

on:
  push:
    branches:
      - main

jobs:
  job-deployment:
    name: Deployment to Server
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Code Checkout
        uses: actions/checkout@v4

      - name: Step 2 - Copy To Win Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASS }}
          port: 22
          source: "index_Ali_Ali.html"
          target: C:\inetpub\wwwroot\


